### ISSUE TITLE
Cấu hình haproxy cho marathon?

### ISSUE THREAD

**Issue by cuongnbms** [tranhuucuong91/autoscaling#3]
Làm thế nào để cấu hình file haproxy để thực hiện load balance cho các ứng dụng của marathon?

**Comment by huanpc** [comment]
- Trong marathon có API hỗ trợ lấy thông tin về các task của Application, từ đó lấy được các port, thêm vào haproxy config file

**Comment by cuongnbms** [comment]
Để cấu hình file haproxy.cfg có thể sử dụng file [servicerouter.py](https://github.com/mesosphere/marathon/blob/master/bin/servicerouter.py). Ví dụ để cấu hình haproxy từ marathon chạy ở địa chỉ localhost:8080 ta dùng lệnh: 
`$ ./servicerouter.py --marathon http://localhost:8080 --haproxy-config /etc/haproxy/haproxy.cfg`

Xem thêm tại [đây](https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing)
