### ISSUE TITLE
Địa chỉ 0.0.0.0 và localhost(127.0.0.1)?

### ISSUE THREAD

**Issue by cuongnbms** [tranhuucuong91/autoscaling#4]
Sự khác nhau giữa 2 địa chỉ trên? Một số lưu ý khi sử dụng trong docker image?

**Comment by huanpc** [comment]
-  Địa chỉ 127.0.0.1 là địa chỉ "loopback", tức là chỉ địa chỉ "fake" của card mạng để các ứng dụng  từ tầng TCP trở lên trên host có thể kết nối đến chính host đấy
- Địa chỉ 0.0.0.0 là địa chỉ "broadcast", tức là khi một server listen ở địa chỉ này nó sẽ nhận mọi kết nối đến
- Điểm khác biệt thấy rõ là nếu server listen ở địa chỉ 127.0.0.1, nó sẽ chỉ nhận các kết nối cũng bắt đầu từ địa chỉ 127.0.0.1, còn nếu server listen ở địa chỉ 0.0.0.0 nó sẽ nhận mọi kết nối từ tất cả các địa chỉ
- [`Reference`](http://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost)
- Đây là ý kiến của mình, có sai thì mọi người đừng gạch đá gì :)
